// Code generated by protoc-gen-go. DO NOT EDIT.
// source: checkin.proto

package service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Checkin struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Wid                  int64    `protobuf:"varint,2,opt,name=Wid,proto3" json:"Wid,omitempty"`
	ActivityId           int64    `protobuf:"varint,3,opt,name=ActivityId,proto3" json:"ActivityId,omitempty"`
	Wuid                 int64    `protobuf:"varint,4,opt,name=Wuid,proto3" json:"Wuid,omitempty"`
	Liner                int64    `protobuf:"varint,5,opt,name=Liner,proto3" json:"Liner,omitempty"`
	Total                int64    `protobuf:"varint,6,opt,name=Total,proto3" json:"Total,omitempty"`
	Lastcheckin          int64    `protobuf:"varint,7,opt,name=Lastcheckin,proto3" json:"Lastcheckin,omitempty"`
	CreatedAt            int64    `protobuf:"varint,10,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,11,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Checkin) Reset()         { *m = Checkin{} }
func (m *Checkin) String() string { return proto.CompactTextString(m) }
func (*Checkin) ProtoMessage()    {}
func (*Checkin) Descriptor() ([]byte, []int) {
	return fileDescriptor_072e71e6019dc001, []int{0}
}

func (m *Checkin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Checkin.Unmarshal(m, b)
}
func (m *Checkin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Checkin.Marshal(b, m, deterministic)
}
func (m *Checkin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Checkin.Merge(m, src)
}
func (m *Checkin) XXX_Size() int {
	return xxx_messageInfo_Checkin.Size(m)
}
func (m *Checkin) XXX_DiscardUnknown() {
	xxx_messageInfo_Checkin.DiscardUnknown(m)
}

var xxx_messageInfo_Checkin proto.InternalMessageInfo

func (m *Checkin) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Checkin) GetWid() int64 {
	if m != nil {
		return m.Wid
	}
	return 0
}

func (m *Checkin) GetActivityId() int64 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *Checkin) GetWuid() int64 {
	if m != nil {
		return m.Wuid
	}
	return 0
}

func (m *Checkin) GetLiner() int64 {
	if m != nil {
		return m.Liner
	}
	return 0
}

func (m *Checkin) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Checkin) GetLastcheckin() int64 {
	if m != nil {
		return m.Lastcheckin
	}
	return 0
}

func (m *Checkin) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Checkin) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type CheckinResponse struct {
	Boolean              bool     `protobuf:"varint,1,opt,name=boolean,proto3" json:"boolean,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckinResponse) Reset()         { *m = CheckinResponse{} }
func (m *CheckinResponse) String() string { return proto.CompactTextString(m) }
func (*CheckinResponse) ProtoMessage()    {}
func (*CheckinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_072e71e6019dc001, []int{1}
}

func (m *CheckinResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckinResponse.Unmarshal(m, b)
}
func (m *CheckinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckinResponse.Marshal(b, m, deterministic)
}
func (m *CheckinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckinResponse.Merge(m, src)
}
func (m *CheckinResponse) XXX_Size() int {
	return xxx_messageInfo_CheckinResponse.Size(m)
}
func (m *CheckinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckinResponse proto.InternalMessageInfo

func (m *CheckinResponse) GetBoolean() bool {
	if m != nil {
		return m.Boolean
	}
	return false
}

func (m *CheckinResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type CheckinQuery struct {
	Index                int64    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Limit                int64    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Wid                  int64    `protobuf:"varint,3,opt,name=wid,proto3" json:"wid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckinQuery) Reset()         { *m = CheckinQuery{} }
func (m *CheckinQuery) String() string { return proto.CompactTextString(m) }
func (*CheckinQuery) ProtoMessage()    {}
func (*CheckinQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_072e71e6019dc001, []int{2}
}

func (m *CheckinQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckinQuery.Unmarshal(m, b)
}
func (m *CheckinQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckinQuery.Marshal(b, m, deterministic)
}
func (m *CheckinQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckinQuery.Merge(m, src)
}
func (m *CheckinQuery) XXX_Size() int {
	return xxx_messageInfo_CheckinQuery.Size(m)
}
func (m *CheckinQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckinQuery.DiscardUnknown(m)
}

var xxx_messageInfo_CheckinQuery proto.InternalMessageInfo

func (m *CheckinQuery) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *CheckinQuery) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *CheckinQuery) GetWid() int64 {
	if m != nil {
		return m.Wid
	}
	return 0
}

type Checkinlist struct {
	Page                 int64      `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int64      `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Checkins             []*Checkin `protobuf:"bytes,3,rep,name=Checkins,proto3" json:"Checkins,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Checkinlist) Reset()         { *m = Checkinlist{} }
func (m *Checkinlist) String() string { return proto.CompactTextString(m) }
func (*Checkinlist) ProtoMessage()    {}
func (*Checkinlist) Descriptor() ([]byte, []int) {
	return fileDescriptor_072e71e6019dc001, []int{3}
}

func (m *Checkinlist) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Checkinlist.Unmarshal(m, b)
}
func (m *Checkinlist) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Checkinlist.Marshal(b, m, deterministic)
}
func (m *Checkinlist) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Checkinlist.Merge(m, src)
}
func (m *Checkinlist) XXX_Size() int {
	return xxx_messageInfo_Checkinlist.Size(m)
}
func (m *Checkinlist) XXX_DiscardUnknown() {
	xxx_messageInfo_Checkinlist.DiscardUnknown(m)
}

var xxx_messageInfo_Checkinlist proto.InternalMessageInfo

func (m *Checkinlist) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *Checkinlist) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Checkinlist) GetCheckins() []*Checkin {
	if m != nil {
		return m.Checkins
	}
	return nil
}

func init() {
	proto.RegisterType((*Checkin)(nil), "service.Checkin")
	proto.RegisterType((*CheckinResponse)(nil), "service.CheckinResponse")
	proto.RegisterType((*CheckinQuery)(nil), "service.CheckinQuery")
	proto.RegisterType((*Checkinlist)(nil), "service.Checkinlist")
}

func init() { proto.RegisterFile("checkin.proto", fileDescriptor_072e71e6019dc001) }

var fileDescriptor_072e71e6019dc001 = []byte{
	// 364 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcf, 0x4e, 0xc2, 0x40,
	0x10, 0xc6, 0x69, 0x0b, 0x14, 0xa7, 0x8a, 0x64, 0x83, 0xc9, 0x86, 0x18, 0x43, 0x7a, 0xe2, 0x60,
	0x6a, 0x82, 0xf1, 0xe4, 0x09, 0x39, 0x98, 0x26, 0xbd, 0x88, 0x1a, 0xce, 0xa5, 0x3b, 0xd1, 0x8d,
	0xb5, 0x6d, 0xba, 0x0b, 0x8a, 0x4f, 0xe4, 0xab, 0xf9, 0x16, 0x66, 0xff, 0x80, 0x04, 0x2e, 0xde,
	0x66, 0x7e, 0xdf, 0xce, 0x74, 0xbf, 0x6f, 0x0b, 0x27, 0xd9, 0x2b, 0x66, 0x6f, 0xbc, 0x88, 0xaa,
	0xba, 0x94, 0x25, 0xf1, 0x05, 0xd6, 0x2b, 0x9e, 0x61, 0xf8, 0xe3, 0x80, 0x3f, 0x35, 0x12, 0xe9,
	0x82, 0x1b, 0x33, 0xea, 0x0c, 0x9d, 0x91, 0x37, 0x73, 0x63, 0x46, 0x7a, 0xe0, 0xcd, 0x39, 0xa3,
	0xae, 0x06, 0xaa, 0x24, 0x17, 0x00, 0x93, 0x4c, 0xf2, 0x15, 0x97, 0xeb, 0x98, 0x51, 0x4f, 0x0b,
	0x3b, 0x84, 0x10, 0x68, 0xce, 0x97, 0x9c, 0xd1, 0xa6, 0x56, 0x74, 0x4d, 0xfa, 0xd0, 0x4a, 0x78,
	0x81, 0x35, 0x6d, 0x69, 0x68, 0x1a, 0x45, 0x9f, 0x4a, 0x99, 0xe6, 0xb4, 0x6d, 0xa8, 0x6e, 0xc8,
	0x10, 0x82, 0x24, 0x15, 0xd2, 0xde, 0x95, 0xfa, 0x5a, 0xdb, 0x45, 0xe4, 0x1c, 0x8e, 0xa6, 0x35,
	0xa6, 0x12, 0xd9, 0x44, 0x52, 0xd0, 0xfa, 0x1f, 0x50, 0xea, 0x73, 0xc5, 0xac, 0x1a, 0x18, 0x75,
	0x0b, 0xc2, 0x5b, 0x38, 0xb5, 0x56, 0x67, 0x28, 0xaa, 0xb2, 0x10, 0x48, 0x28, 0xf8, 0x8b, 0xb2,
	0xcc, 0x31, 0x2d, 0xb4, 0xef, 0xce, 0x6c, 0xd3, 0xaa, 0x30, 0xb6, 0xde, 0x5d, 0xce, 0xc2, 0x04,
	0x8e, 0xed, 0xf0, 0xc3, 0x12, 0xeb, 0xb5, 0x32, 0xc0, 0x0b, 0x86, 0x9f, 0x36, 0x2f, 0xd3, 0x28,
	0x9a, 0xf3, 0x77, 0x2e, 0xed, 0xa0, 0x69, 0x54, 0x90, 0x1f, 0x7c, 0x93, 0x97, 0x2a, 0xc3, 0x0c,
	0x02, 0xbb, 0x2d, 0xe7, 0x42, 0xaa, 0xdc, 0xaa, 0xf4, 0x05, 0xed, 0x2e, 0x5d, 0x2b, 0x26, 0xf8,
	0x17, 0xda, 0x4d, 0xba, 0x26, 0x97, 0xd0, 0xb1, 0x63, 0x82, 0x7a, 0x43, 0x6f, 0x14, 0x8c, 0x7b,
	0x91, 0x7d, 0xc9, 0x68, 0x63, 0x6d, 0x7b, 0x62, 0xfc, 0xed, 0x40, 0xd7, 0x36, 0x8f, 0xe6, 0x10,
	0xb9, 0x02, 0xff, 0x1e, 0xe5, 0x9d, 0x7a, 0xab, 0x83, 0xc9, 0xc1, 0x01, 0x09, 0x1b, 0xe4, 0x06,
	0x9a, 0x89, 0xba, 0xe1, 0xd9, 0xbe, 0xa6, 0x53, 0x18, 0xf4, 0xf7, 0xb1, 0xb2, 0x13, 0x36, 0x48,
	0x04, 0xed, 0xb8, 0x10, 0x58, 0xcb, 0xff, 0x7d, 0x66, 0xd1, 0xd6, 0xbf, 0xe5, 0xf5, 0x6f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xcd, 0xb6, 0xcb, 0x00, 0xa7, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CheckinServiceClient is the client API for CheckinService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CheckinServiceClient interface {
	GetById(ctx context.Context, in *Checkin, opts ...grpc.CallOption) (*Checkin, error)
	List(ctx context.Context, in *CheckinQuery, opts ...grpc.CallOption) (*Checkinlist, error)
	Insert(ctx context.Context, in *Checkin, opts ...grpc.CallOption) (*Checkin, error)
}

type checkinServiceClient struct {
	cc *grpc.ClientConn
}

func NewCheckinServiceClient(cc *grpc.ClientConn) CheckinServiceClient {
	return &checkinServiceClient{cc}
}

func (c *checkinServiceClient) GetById(ctx context.Context, in *Checkin, opts ...grpc.CallOption) (*Checkin, error) {
	out := new(Checkin)
	err := c.cc.Invoke(ctx, "/service.CheckinService/GetById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkinServiceClient) List(ctx context.Context, in *CheckinQuery, opts ...grpc.CallOption) (*Checkinlist, error) {
	out := new(Checkinlist)
	err := c.cc.Invoke(ctx, "/service.CheckinService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkinServiceClient) Insert(ctx context.Context, in *Checkin, opts ...grpc.CallOption) (*Checkin, error) {
	out := new(Checkin)
	err := c.cc.Invoke(ctx, "/service.CheckinService/Insert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CheckinServiceServer is the server API for CheckinService service.
type CheckinServiceServer interface {
	GetById(context.Context, *Checkin) (*Checkin, error)
	List(context.Context, *CheckinQuery) (*Checkinlist, error)
	Insert(context.Context, *Checkin) (*Checkin, error)
}

// UnimplementedCheckinServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCheckinServiceServer struct {
}

func (*UnimplementedCheckinServiceServer) GetById(ctx context.Context, req *Checkin) (*Checkin, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetById not implemented")
}
func (*UnimplementedCheckinServiceServer) List(ctx context.Context, req *CheckinQuery) (*Checkinlist, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedCheckinServiceServer) Insert(ctx context.Context, req *Checkin) (*Checkin, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Insert not implemented")
}

func RegisterCheckinServiceServer(s *grpc.Server, srv CheckinServiceServer) {
	s.RegisterService(&_CheckinService_serviceDesc, srv)
}

func _CheckinService_GetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Checkin)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckinServiceServer).GetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.CheckinService/GetById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckinServiceServer).GetById(ctx, req.(*Checkin))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckinService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckinQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckinServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.CheckinService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckinServiceServer).List(ctx, req.(*CheckinQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckinService_Insert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Checkin)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckinServiceServer).Insert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.CheckinService/Insert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckinServiceServer).Insert(ctx, req.(*Checkin))
	}
	return interceptor(ctx, in, info, handler)
}

var _CheckinService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.CheckinService",
	HandlerType: (*CheckinServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetById",
			Handler:    _CheckinService_GetById_Handler,
		},
		{
			MethodName: "List",
			Handler:    _CheckinService_List_Handler,
		},
		{
			MethodName: "Insert",
			Handler:    _CheckinService_Insert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "checkin.proto",
}
