// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/checkin.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Checkin struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Wid                  int64    `protobuf:"varint,2,opt,name=wid,proto3" json:"wid,omitempty"`
	ActivityId           int64    `protobuf:"varint,3,opt,name=activityId,proto3" json:"activityId,omitempty"`
	Wuid                 int64    `protobuf:"varint,4,opt,name=wuid,proto3" json:"wuid,omitempty"`
	Liner                int64    `protobuf:"varint,5,opt,name=liner,proto3" json:"liner,omitempty"`
	Total                int64    `protobuf:"varint,6,opt,name=total,proto3" json:"total,omitempty"`
	Lastcheckin          int64    `protobuf:"varint,7,opt,name=lastcheckin,proto3" json:"lastcheckin,omitempty"`
	CreatedAt            int64    `protobuf:"varint,8,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,9,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Checkin) Reset()         { *m = Checkin{} }
func (m *Checkin) String() string { return proto.CompactTextString(m) }
func (*Checkin) ProtoMessage()    {}
func (*Checkin) Descriptor() ([]byte, []int) {
	return fileDescriptor_89899ba32f290dc3, []int{0}
}

func (m *Checkin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Checkin.Unmarshal(m, b)
}
func (m *Checkin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Checkin.Marshal(b, m, deterministic)
}
func (m *Checkin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Checkin.Merge(m, src)
}
func (m *Checkin) XXX_Size() int {
	return xxx_messageInfo_Checkin.Size(m)
}
func (m *Checkin) XXX_DiscardUnknown() {
	xxx_messageInfo_Checkin.DiscardUnknown(m)
}

var xxx_messageInfo_Checkin proto.InternalMessageInfo

func (m *Checkin) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Checkin) GetWid() int64 {
	if m != nil {
		return m.Wid
	}
	return 0
}

func (m *Checkin) GetActivityId() int64 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *Checkin) GetWuid() int64 {
	if m != nil {
		return m.Wuid
	}
	return 0
}

func (m *Checkin) GetLiner() int64 {
	if m != nil {
		return m.Liner
	}
	return 0
}

func (m *Checkin) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Checkin) GetLastcheckin() int64 {
	if m != nil {
		return m.Lastcheckin
	}
	return 0
}

func (m *Checkin) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Checkin) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type CheckinList struct {
	Index                int64      `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Limit                int64      `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Total                int64      `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Checkins             []*Checkin `protobuf:"bytes,4,rep,name=checkins,proto3" json:"checkins,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CheckinList) Reset()         { *m = CheckinList{} }
func (m *CheckinList) String() string { return proto.CompactTextString(m) }
func (*CheckinList) ProtoMessage()    {}
func (*CheckinList) Descriptor() ([]byte, []int) {
	return fileDescriptor_89899ba32f290dc3, []int{1}
}

func (m *CheckinList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckinList.Unmarshal(m, b)
}
func (m *CheckinList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckinList.Marshal(b, m, deterministic)
}
func (m *CheckinList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckinList.Merge(m, src)
}
func (m *CheckinList) XXX_Size() int {
	return xxx_messageInfo_CheckinList.Size(m)
}
func (m *CheckinList) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckinList.DiscardUnknown(m)
}

var xxx_messageInfo_CheckinList proto.InternalMessageInfo

func (m *CheckinList) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *CheckinList) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *CheckinList) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *CheckinList) GetCheckins() []*Checkin {
	if m != nil {
		return m.Checkins
	}
	return nil
}

func init() {
	proto.RegisterType((*Checkin)(nil), "pb.Checkin")
	proto.RegisterType((*CheckinList)(nil), "pb.CheckinList")
}

func init() { proto.RegisterFile("pb/checkin.proto", fileDescriptor_89899ba32f290dc3) }

var fileDescriptor_89899ba32f290dc3 = []byte{
	// 241 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0x49, 0x36, 0xfd, 0x37, 0x01, 0x29, 0x83, 0x87, 0x39, 0x88, 0x84, 0x5e, 0xec, 0x29,
	0x82, 0x3e, 0x81, 0x78, 0x12, 0x3c, 0xf5, 0x0d, 0x92, 0xec, 0x82, 0x83, 0x31, 0x59, 0x92, 0xa9,
	0xad, 0x8f, 0xec, 0x5b, 0x94, 0xcc, 0x2e, 0x6d, 0x6e, 0xf3, 0xfd, 0x7e, 0x87, 0xfd, 0xbe, 0x85,
	0xad, 0xaf, 0x9f, 0x9b, 0x2f, 0xd7, 0x7c, 0x73, 0x57, 0xfa, 0xa1, 0x97, 0x1e, 0x53, 0x5f, 0xef,
	0xfe, 0x13, 0x58, 0xbd, 0x07, 0x8a, 0x77, 0x90, 0xb2, 0xa5, 0xa4, 0x48, 0xf6, 0xe6, 0x90, 0xb2,
	0xc5, 0x2d, 0x98, 0x13, 0x5b, 0x4a, 0x15, 0x4c, 0x27, 0x3e, 0x02, 0x54, 0x8d, 0xf0, 0x2f, 0xcb,
	0xdf, 0x87, 0x25, 0xa3, 0x62, 0x46, 0x10, 0x21, 0x3b, 0x1d, 0xd9, 0x52, 0xa6, 0x46, 0x6f, 0xbc,
	0x87, 0x45, 0xcb, 0x9d, 0x1b, 0x68, 0xa1, 0x30, 0x84, 0x89, 0x4a, 0x2f, 0x55, 0x4b, 0xcb, 0x40,
	0x35, 0x60, 0x01, 0x79, 0x5b, 0x8d, 0x12, 0x6b, 0xd2, 0x4a, 0xdd, 0x1c, 0xe1, 0x03, 0x6c, 0x9a,
	0xc1, 0x55, 0xe2, 0xec, 0x9b, 0xd0, 0x5a, 0xfd, 0x0d, 0x4c, 0xf6, 0xe8, 0x6d, 0xb4, 0x9b, 0x60,
	0xaf, 0x60, 0x77, 0x86, 0x3c, 0x4e, 0xfd, 0xe4, 0x51, 0xa6, 0x0a, 0xdc, 0x59, 0x77, 0x8e, 0x8b,
	0x43, 0x08, 0x75, 0x7f, 0x58, 0xe2, 0xec, 0x10, 0x6e, 0x75, 0xcd, 0xbc, 0xee, 0x13, 0xac, 0x63,
	0xaf, 0x91, 0xb2, 0xc2, 0xec, 0xf3, 0x97, 0xbc, 0xf4, 0x75, 0x19, 0x1f, 0x39, 0x5c, 0x65, 0xbd,
	0xd4, 0x0f, 0x7f, 0xbd, 0x04, 0x00, 0x00, 0xff, 0xff, 0x69, 0x98, 0x04, 0x49, 0x84, 0x01, 0x00,
	0x00,
}
