// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/lottery.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Lottery struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Wid                  int64    `protobuf:"varint,2,opt,name=wid,proto3" json:"wid,omitempty"`
	ActivityId           int64    `protobuf:"varint,3,opt,name=activityId,proto3" json:"activityId,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Desc                 string   `protobuf:"bytes,5,opt,name=desc,proto3" json:"desc,omitempty"`
	TotalNum             int64    `protobuf:"varint,6,opt,name=totalNum,proto3" json:"totalNum,omitempty"`
	ClaimedNum           int64    `protobuf:"varint,7,opt,name=claimedNum,proto3" json:"claimedNum,omitempty"`
	Probability          int32    `protobuf:"varint,8,opt,name=probability,proto3" json:"probability,omitempty"`
	FirstCodeId          int64    `protobuf:"varint,9,opt,name=firstCodeId,proto3" json:"firstCodeId,omitempty"`
	Level                string   `protobuf:"bytes,10,opt,name=level,proto3" json:"level,omitempty"`
	CreatedAt            int64    `protobuf:"varint,11,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,12,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Lottery) Reset()         { *m = Lottery{} }
func (m *Lottery) String() string { return proto.CompactTextString(m) }
func (*Lottery) ProtoMessage()    {}
func (*Lottery) Descriptor() ([]byte, []int) {
	return fileDescriptor_80611df2888f5971, []int{0}
}

func (m *Lottery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lottery.Unmarshal(m, b)
}
func (m *Lottery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lottery.Marshal(b, m, deterministic)
}
func (m *Lottery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lottery.Merge(m, src)
}
func (m *Lottery) XXX_Size() int {
	return xxx_messageInfo_Lottery.Size(m)
}
func (m *Lottery) XXX_DiscardUnknown() {
	xxx_messageInfo_Lottery.DiscardUnknown(m)
}

var xxx_messageInfo_Lottery proto.InternalMessageInfo

func (m *Lottery) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Lottery) GetWid() int64 {
	if m != nil {
		return m.Wid
	}
	return 0
}

func (m *Lottery) GetActivityId() int64 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *Lottery) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Lottery) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *Lottery) GetTotalNum() int64 {
	if m != nil {
		return m.TotalNum
	}
	return 0
}

func (m *Lottery) GetClaimedNum() int64 {
	if m != nil {
		return m.ClaimedNum
	}
	return 0
}

func (m *Lottery) GetProbability() int32 {
	if m != nil {
		return m.Probability
	}
	return 0
}

func (m *Lottery) GetFirstCodeId() int64 {
	if m != nil {
		return m.FirstCodeId
	}
	return 0
}

func (m *Lottery) GetLevel() string {
	if m != nil {
		return m.Level
	}
	return ""
}

func (m *Lottery) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Lottery) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type LotteryList struct {
	Index                int64      `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Limit                int64      `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Total                int64      `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Lotteries            []*Lottery `protobuf:"bytes,4,rep,name=lotteries,proto3" json:"lotteries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *LotteryList) Reset()         { *m = LotteryList{} }
func (m *LotteryList) String() string { return proto.CompactTextString(m) }
func (*LotteryList) ProtoMessage()    {}
func (*LotteryList) Descriptor() ([]byte, []int) {
	return fileDescriptor_80611df2888f5971, []int{1}
}

func (m *LotteryList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LotteryList.Unmarshal(m, b)
}
func (m *LotteryList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LotteryList.Marshal(b, m, deterministic)
}
func (m *LotteryList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LotteryList.Merge(m, src)
}
func (m *LotteryList) XXX_Size() int {
	return xxx_messageInfo_LotteryList.Size(m)
}
func (m *LotteryList) XXX_DiscardUnknown() {
	xxx_messageInfo_LotteryList.DiscardUnknown(m)
}

var xxx_messageInfo_LotteryList proto.InternalMessageInfo

func (m *LotteryList) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *LotteryList) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *LotteryList) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *LotteryList) GetLotteries() []*Lottery {
	if m != nil {
		return m.Lotteries
	}
	return nil
}

type RequestWidAndActivityId struct {
	Wid                  int64    `protobuf:"varint,1,opt,name=wid,proto3" json:"wid,omitempty"`
	ActivityId           int64    `protobuf:"varint,2,opt,name=activityId,proto3" json:"activityId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestWidAndActivityId) Reset()         { *m = RequestWidAndActivityId{} }
func (m *RequestWidAndActivityId) String() string { return proto.CompactTextString(m) }
func (*RequestWidAndActivityId) ProtoMessage()    {}
func (*RequestWidAndActivityId) Descriptor() ([]byte, []int) {
	return fileDescriptor_80611df2888f5971, []int{2}
}

func (m *RequestWidAndActivityId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestWidAndActivityId.Unmarshal(m, b)
}
func (m *RequestWidAndActivityId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestWidAndActivityId.Marshal(b, m, deterministic)
}
func (m *RequestWidAndActivityId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestWidAndActivityId.Merge(m, src)
}
func (m *RequestWidAndActivityId) XXX_Size() int {
	return xxx_messageInfo_RequestWidAndActivityId.Size(m)
}
func (m *RequestWidAndActivityId) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestWidAndActivityId.DiscardUnknown(m)
}

var xxx_messageInfo_RequestWidAndActivityId proto.InternalMessageInfo

func (m *RequestWidAndActivityId) GetWid() int64 {
	if m != nil {
		return m.Wid
	}
	return 0
}

func (m *RequestWidAndActivityId) GetActivityId() int64 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func init() {
	proto.RegisterType((*Lottery)(nil), "pb.Lottery")
	proto.RegisterType((*LotteryList)(nil), "pb.LotteryList")
	proto.RegisterType((*RequestWidAndActivityId)(nil), "pb.requestWidAndActivityId")
}

func init() { proto.RegisterFile("pb/lottery.proto", fileDescriptor_80611df2888f5971) }

var fileDescriptor_80611df2888f5971 = []byte{
	// 325 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x4f, 0x6b, 0xab, 0x50,
	0x10, 0xc5, 0x51, 0xf3, 0xcf, 0xf1, 0xf1, 0x08, 0x97, 0x07, 0xef, 0x52, 0x4a, 0x91, 0xac, 0xec,
	0x26, 0x85, 0xf6, 0x13, 0x84, 0xae, 0x42, 0x43, 0x17, 0x6e, 0xba, 0x56, 0x67, 0x0a, 0x03, 0x1a,
	0xad, 0x4e, 0xd2, 0xa6, 0xdf, 0xaf, 0xdf, 0xab, 0xdc, 0x3f, 0xc4, 0x50, 0xe8, 0x6e, 0xce, 0xef,
	0xe8, 0x3d, 0x3a, 0xe7, 0xc2, 0xb2, 0x2b, 0xef, 0xea, 0x56, 0x84, 0xfa, 0xd3, 0xba, 0xeb, 0x5b,
	0x69, 0x55, 0xd8, 0x95, 0xab, 0xaf, 0x10, 0xe6, 0x3b, 0x47, 0xd5, 0x5f, 0x08, 0x19, 0x75, 0x90,
	0x06, 0x59, 0x94, 0x87, 0x8c, 0x6a, 0x09, 0xd1, 0x3b, 0xa3, 0x0e, 0x2d, 0x30, 0xa3, 0xba, 0x01,
	0x28, 0x2a, 0xe1, 0x23, 0xcb, 0x69, 0x8b, 0x3a, 0xb2, 0xc6, 0x05, 0x51, 0x0a, 0x26, 0xfb, 0xa2,
	0x21, 0x3d, 0x49, 0x83, 0x2c, 0xce, 0xed, 0x6c, 0x18, 0xd2, 0x50, 0xe9, 0xa9, 0x63, 0x66, 0x56,
	0x57, 0xb0, 0x90, 0x56, 0x8a, 0xfa, 0xf9, 0xd0, 0xe8, 0x99, 0x3d, 0xe5, 0xac, 0x4d, 0x46, 0x55,
	0x17, 0xdc, 0x10, 0x1a, 0x77, 0xee, 0x32, 0x46, 0xa2, 0x52, 0x48, 0xba, 0xbe, 0x2d, 0x8b, 0x92,
	0x6b, 0x96, 0x93, 0x5e, 0xa4, 0x41, 0x36, 0xcd, 0x2f, 0x91, 0x79, 0xe2, 0x95, 0xfb, 0x41, 0x1e,
	0x5b, 0xa4, 0x2d, 0xea, 0xd8, 0x1e, 0x71, 0x89, 0xd4, 0x3f, 0x98, 0xd6, 0x74, 0xa4, 0x5a, 0x83,
	0xfd, 0x28, 0x27, 0xd4, 0x35, 0xc4, 0x55, 0x4f, 0x85, 0x10, 0x6e, 0x44, 0x27, 0xf6, 0xad, 0x11,
	0x18, 0xf7, 0xd0, 0xa1, 0x77, 0xff, 0x38, 0xf7, 0x0c, 0x56, 0x9f, 0x90, 0xf8, 0x35, 0xee, 0x78,
	0x10, 0x13, 0xc0, 0x7b, 0xa4, 0x0f, 0xbf, 0x4d, 0x27, 0x6c, 0x2c, 0x37, 0x2c, 0x7e, 0xa5, 0x4e,
	0x18, 0x6a, 0x7f, 0xde, 0xef, 0xd3, 0x09, 0x75, 0x0b, 0xb1, 0x6b, 0x8b, 0x69, 0xd0, 0x93, 0x34,
	0xca, 0x92, 0xfb, 0x64, 0xdd, 0x95, 0x6b, 0x9f, 0x92, 0x8f, 0xee, 0xea, 0x09, 0xfe, 0xf7, 0xf4,
	0x76, 0xa0, 0x41, 0x5e, 0x18, 0x37, 0x7b, 0xdc, 0x8c, 0x85, 0xf8, 0x0a, 0x83, 0xdf, 0x2a, 0x0c,
	0x7f, 0x56, 0x58, 0xce, 0xec, 0xdd, 0x78, 0xf8, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x38, 0x9f, 0xee,
	0xb3, 0x2f, 0x02, 0x00, 0x00,
}
