// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/prizeHistory.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PrizeHistory struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Wuid                 int64    `protobuf:"varint,2,opt,name=wuid,proto3" json:"wuid,omitempty"`
	ActivityId           int64    `protobuf:"varint,3,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	Prize                string   `protobuf:"bytes,4,opt,name=prize,proto3" json:"prize,omitempty"`
	Code                 string   `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
	Level                string   `protobuf:"bytes,6,opt,name=level,proto3" json:"level,omitempty"`
	CreatedAt            int64    `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrizeHistory) Reset()         { *m = PrizeHistory{} }
func (m *PrizeHistory) String() string { return proto.CompactTextString(m) }
func (*PrizeHistory) ProtoMessage()    {}
func (*PrizeHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_a90130f5e3134c15, []int{0}
}

func (m *PrizeHistory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrizeHistory.Unmarshal(m, b)
}
func (m *PrizeHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrizeHistory.Marshal(b, m, deterministic)
}
func (m *PrizeHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrizeHistory.Merge(m, src)
}
func (m *PrizeHistory) XXX_Size() int {
	return xxx_messageInfo_PrizeHistory.Size(m)
}
func (m *PrizeHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_PrizeHistory.DiscardUnknown(m)
}

var xxx_messageInfo_PrizeHistory proto.InternalMessageInfo

func (m *PrizeHistory) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PrizeHistory) GetWuid() int64 {
	if m != nil {
		return m.Wuid
	}
	return 0
}

func (m *PrizeHistory) GetActivityId() int64 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *PrizeHistory) GetPrize() string {
	if m != nil {
		return m.Prize
	}
	return ""
}

func (m *PrizeHistory) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *PrizeHistory) GetLevel() string {
	if m != nil {
		return m.Level
	}
	return ""
}

func (m *PrizeHistory) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

type PrizeHistoryList struct {
	Index                int64           `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Limit                int64           `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Total                int64           `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Histories            []*PrizeHistory `protobuf:"bytes,4,rep,name=histories,proto3" json:"histories,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PrizeHistoryList) Reset()         { *m = PrizeHistoryList{} }
func (m *PrizeHistoryList) String() string { return proto.CompactTextString(m) }
func (*PrizeHistoryList) ProtoMessage()    {}
func (*PrizeHistoryList) Descriptor() ([]byte, []int) {
	return fileDescriptor_a90130f5e3134c15, []int{1}
}

func (m *PrizeHistoryList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrizeHistoryList.Unmarshal(m, b)
}
func (m *PrizeHistoryList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrizeHistoryList.Marshal(b, m, deterministic)
}
func (m *PrizeHistoryList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrizeHistoryList.Merge(m, src)
}
func (m *PrizeHistoryList) XXX_Size() int {
	return xxx_messageInfo_PrizeHistoryList.Size(m)
}
func (m *PrizeHistoryList) XXX_DiscardUnknown() {
	xxx_messageInfo_PrizeHistoryList.DiscardUnknown(m)
}

var xxx_messageInfo_PrizeHistoryList proto.InternalMessageInfo

func (m *PrizeHistoryList) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *PrizeHistoryList) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *PrizeHistoryList) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *PrizeHistoryList) GetHistories() []*PrizeHistory {
	if m != nil {
		return m.Histories
	}
	return nil
}

type RequestOneByActivityWuid struct {
	Wuid                 int64    `protobuf:"varint,1,opt,name=wuid,proto3" json:"wuid,omitempty"`
	ActivityId           int64    `protobuf:"varint,2,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestOneByActivityWuid) Reset()         { *m = RequestOneByActivityWuid{} }
func (m *RequestOneByActivityWuid) String() string { return proto.CompactTextString(m) }
func (*RequestOneByActivityWuid) ProtoMessage()    {}
func (*RequestOneByActivityWuid) Descriptor() ([]byte, []int) {
	return fileDescriptor_a90130f5e3134c15, []int{2}
}

func (m *RequestOneByActivityWuid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestOneByActivityWuid.Unmarshal(m, b)
}
func (m *RequestOneByActivityWuid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestOneByActivityWuid.Marshal(b, m, deterministic)
}
func (m *RequestOneByActivityWuid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestOneByActivityWuid.Merge(m, src)
}
func (m *RequestOneByActivityWuid) XXX_Size() int {
	return xxx_messageInfo_RequestOneByActivityWuid.Size(m)
}
func (m *RequestOneByActivityWuid) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestOneByActivityWuid.DiscardUnknown(m)
}

var xxx_messageInfo_RequestOneByActivityWuid proto.InternalMessageInfo

func (m *RequestOneByActivityWuid) GetWuid() int64 {
	if m != nil {
		return m.Wuid
	}
	return 0
}

func (m *RequestOneByActivityWuid) GetActivityId() int64 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func init() {
	proto.RegisterType((*PrizeHistory)(nil), "pb.prize_history")
	proto.RegisterType((*PrizeHistoryList)(nil), "pb.prize_history_list")
	proto.RegisterType((*RequestOneByActivityWuid)(nil), "pb.request_one_by_activity_wuid")
}

func init() { proto.RegisterFile("pb/prizeHistory.proto", fileDescriptor_a90130f5e3134c15) }

var fileDescriptor_a90130f5e3134c15 = []byte{
	// 271 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x51, 0x41, 0x4a, 0xc4, 0x40,
	0x10, 0x64, 0xb2, 0xd9, 0x95, 0xf4, 0xa2, 0xe0, 0xa0, 0x30, 0x07, 0xc5, 0x90, 0x53, 0x4e, 0x59,
	0xd0, 0x17, 0x78, 0xd3, 0x6b, 0x7c, 0xc0, 0x90, 0x64, 0x1a, 0x6c, 0x88, 0x3b, 0x31, 0xe9, 0x5d,
	0x8d, 0x1f, 0xf0, 0x41, 0x7e, 0x50, 0xd2, 0x93, 0x55, 0x56, 0xf0, 0xd6, 0x55, 0x5d, 0x54, 0xd7,
	0xd4, 0xc0, 0x65, 0x57, 0x6f, 0xba, 0x9e, 0x3e, 0xf0, 0x81, 0x06, 0xf6, 0xfd, 0x58, 0x74, 0xbd,
	0x67, 0xaf, 0xa3, 0xae, 0xce, 0xbe, 0x14, 0x9c, 0xca, 0xca, 0x3e, 0x87, 0x9d, 0x3e, 0x83, 0x88,
	0x9c, 0x51, 0xa9, 0xca, 0x17, 0x65, 0x44, 0x4e, 0x6b, 0x88, 0xdf, 0x76, 0xe4, 0x4c, 0x24, 0x8c,
	0xcc, 0xfa, 0x06, 0xd6, 0x55, 0xc3, 0xb4, 0x27, 0x1e, 0x2d, 0x39, 0xb3, 0x90, 0x15, 0x1c, 0xa8,
	0x47, 0xa7, 0x2f, 0x60, 0x29, 0xae, 0x26, 0x4e, 0x55, 0x9e, 0x94, 0x01, 0x4c, 0x56, 0x8d, 0x77,
	0x68, 0x96, 0x42, 0xca, 0x3c, 0x29, 0x5b, 0xdc, 0x63, 0x6b, 0x56, 0x41, 0x29, 0x40, 0x5f, 0x03,
	0x34, 0x3d, 0x56, 0x8c, 0xce, 0x56, 0x6c, 0x4e, 0xc4, 0x3f, 0x99, 0x99, 0x7b, 0xce, 0x3e, 0x15,
	0xe8, 0xa3, 0xd4, 0xb6, 0xa5, 0x81, 0x27, 0x2f, 0xda, 0x3a, 0x7c, 0x9f, 0xd3, 0x07, 0x20, 0x17,
	0xe8, 0x85, 0x78, 0x7e, 0x41, 0x00, 0x13, 0xcb, 0x9e, 0xab, 0x76, 0x0e, 0x1f, 0x80, 0xde, 0x40,
	0x12, 0x1c, 0x09, 0x07, 0x13, 0xa7, 0x8b, 0x7c, 0x7d, 0x7b, 0x5e, 0x74, 0x75, 0x71, 0x74, 0xac,
	0xfc, 0xd5, 0x64, 0x4f, 0x70, 0xd5, 0xe3, 0xeb, 0x0e, 0x07, 0xb6, 0x7e, 0x8b, 0xb6, 0x1e, 0xed,
	0x4f, 0x31, 0xd2, 0xd4, 0xa1, 0x3d, 0xf5, 0x7f, 0x7b, 0xd1, 0xdf, 0xf6, 0xea, 0x95, 0xfc, 0xcf,
	0xdd, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x36, 0x11, 0xd9, 0x22, 0xb8, 0x01, 0x00, 0x00,
}
