// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/prize.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Prize struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Wid                  int64    `protobuf:"varint,2,opt,name=wid,proto3" json:"wid,omitempty"`
	ActivityId           int64    `protobuf:"varint,3,opt,name=activityId,proto3" json:"activityId,omitempty"`
	Used                 bool     `protobuf:"varint,4,opt,name=used,proto3" json:"used,omitempty"`
	Code                 string   `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
	Level                string   `protobuf:"bytes,6,opt,name=level,proto3" json:"level,omitempty"`
	CreatedAt            int64    `protobuf:"varint,7,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Prize) Reset()         { *m = Prize{} }
func (m *Prize) String() string { return proto.CompactTextString(m) }
func (*Prize) ProtoMessage()    {}
func (*Prize) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4be5d299aa50fc9, []int{0}
}

func (m *Prize) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Prize.Unmarshal(m, b)
}
func (m *Prize) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Prize.Marshal(b, m, deterministic)
}
func (m *Prize) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Prize.Merge(m, src)
}
func (m *Prize) XXX_Size() int {
	return xxx_messageInfo_Prize.Size(m)
}
func (m *Prize) XXX_DiscardUnknown() {
	xxx_messageInfo_Prize.DiscardUnknown(m)
}

var xxx_messageInfo_Prize proto.InternalMessageInfo

func (m *Prize) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Prize) GetWid() int64 {
	if m != nil {
		return m.Wid
	}
	return 0
}

func (m *Prize) GetActivityId() int64 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *Prize) GetUsed() bool {
	if m != nil {
		return m.Used
	}
	return false
}

func (m *Prize) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Prize) GetLevel() string {
	if m != nil {
		return m.Level
	}
	return ""
}

func (m *Prize) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

type PrizeList struct {
	Index                int64    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Limit                int64    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Total                int64    `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Prizes               []*Prize `protobuf:"bytes,4,rep,name=prizes,proto3" json:"prizes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrizeList) Reset()         { *m = PrizeList{} }
func (m *PrizeList) String() string { return proto.CompactTextString(m) }
func (*PrizeList) ProtoMessage()    {}
func (*PrizeList) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4be5d299aa50fc9, []int{1}
}

func (m *PrizeList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrizeList.Unmarshal(m, b)
}
func (m *PrizeList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrizeList.Marshal(b, m, deterministic)
}
func (m *PrizeList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrizeList.Merge(m, src)
}
func (m *PrizeList) XXX_Size() int {
	return xxx_messageInfo_PrizeList.Size(m)
}
func (m *PrizeList) XXX_DiscardUnknown() {
	xxx_messageInfo_PrizeList.DiscardUnknown(m)
}

var xxx_messageInfo_PrizeList proto.InternalMessageInfo

func (m *PrizeList) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *PrizeList) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *PrizeList) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *PrizeList) GetPrizes() []*Prize {
	if m != nil {
		return m.Prizes
	}
	return nil
}

type ChooseOneUsedPrize struct {
	ActivityId           int64    `protobuf:"varint,1,opt,name=activityId,proto3" json:"activityId,omitempty"`
	Level                string   `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	IdGt                 int64    `protobuf:"varint,3,opt,name=idGt,proto3" json:"idGt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChooseOneUsedPrize) Reset()         { *m = ChooseOneUsedPrize{} }
func (m *ChooseOneUsedPrize) String() string { return proto.CompactTextString(m) }
func (*ChooseOneUsedPrize) ProtoMessage()    {}
func (*ChooseOneUsedPrize) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4be5d299aa50fc9, []int{2}
}

func (m *ChooseOneUsedPrize) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChooseOneUsedPrize.Unmarshal(m, b)
}
func (m *ChooseOneUsedPrize) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChooseOneUsedPrize.Marshal(b, m, deterministic)
}
func (m *ChooseOneUsedPrize) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChooseOneUsedPrize.Merge(m, src)
}
func (m *ChooseOneUsedPrize) XXX_Size() int {
	return xxx_messageInfo_ChooseOneUsedPrize.Size(m)
}
func (m *ChooseOneUsedPrize) XXX_DiscardUnknown() {
	xxx_messageInfo_ChooseOneUsedPrize.DiscardUnknown(m)
}

var xxx_messageInfo_ChooseOneUsedPrize proto.InternalMessageInfo

func (m *ChooseOneUsedPrize) GetActivityId() int64 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *ChooseOneUsedPrize) GetLevel() string {
	if m != nil {
		return m.Level
	}
	return ""
}

func (m *ChooseOneUsedPrize) GetIdGt() int64 {
	if m != nil {
		return m.IdGt
	}
	return 0
}

func init() {
	proto.RegisterType((*Prize)(nil), "pb.Prize")
	proto.RegisterType((*PrizeList)(nil), "pb.PrizeList")
	proto.RegisterType((*ChooseOneUsedPrize)(nil), "pb.ChooseOneUsedPrize")
}

func init() { proto.RegisterFile("pb/prize.proto", fileDescriptor_d4be5d299aa50fc9) }

var fileDescriptor_d4be5d299aa50fc9 = []byte{
	// 264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xcd, 0x4a, 0xfd, 0x40,
	0x0c, 0xc5, 0x99, 0x7e, 0xfd, 0xff, 0x8d, 0x70, 0x91, 0xe0, 0x62, 0x16, 0x22, 0xb5, 0xab, 0xae,
	0x2a, 0xe8, 0x13, 0x88, 0x0b, 0x11, 0x04, 0xa5, 0xe0, 0x56, 0x68, 0x3b, 0x01, 0x03, 0xf5, 0xce,
	0xd0, 0xc6, 0xeb, 0xc7, 0xfb, 0xf8, 0x9e, 0xd2, 0xb4, 0xe8, 0x15, 0x77, 0xe7, 0xfc, 0x02, 0x99,
	0x93, 0x33, 0xb0, 0x09, 0xdd, 0x59, 0x18, 0xf9, 0x83, 0xea, 0x30, 0x7a, 0xf1, 0x18, 0x85, 0xae,
	0xfc, 0x34, 0x90, 0xde, 0xcf, 0x0c, 0x37, 0x10, 0xb1, 0xb3, 0xa6, 0x30, 0x55, 0xdc, 0x44, 0xec,
	0xf0, 0x10, 0xe2, 0x57, 0x76, 0x36, 0x52, 0x30, 0x4b, 0x3c, 0x01, 0x68, 0x7b, 0xe1, 0x1d, 0xcb,
	0xfb, 0x8d, 0xb3, 0xb1, 0x0e, 0xf6, 0x08, 0x22, 0x24, 0x2f, 0x13, 0x39, 0x9b, 0x14, 0xa6, 0xfa,
	0xdf, 0xa8, 0x9e, 0x59, 0xef, 0x1d, 0xd9, 0xb4, 0x30, 0x55, 0xde, 0xa8, 0xc6, 0x23, 0x48, 0x07,
	0xda, 0xd1, 0x60, 0x33, 0x85, 0x8b, 0xc1, 0x63, 0xc8, 0xfb, 0x91, 0x5a, 0x21, 0x77, 0x29, 0xf6,
	0x9f, 0x2e, 0xff, 0x01, 0x65, 0x80, 0x5c, 0x63, 0xde, 0xf2, 0x24, 0xf3, 0x02, 0xde, 0x3a, 0x7a,
	0x5b, 0xd3, 0x2e, 0x46, 0xd7, 0xf2, 0x33, 0xcb, 0x1a, 0x79, 0x31, 0x33, 0x15, 0x2f, 0xed, 0xb0,
	0xe6, 0x5d, 0x0c, 0x9e, 0x42, 0xa6, 0x4d, 0x4c, 0x36, 0x29, 0xe2, 0xea, 0xe0, 0x3c, 0xaf, 0x43,
	0x57, 0xeb, 0x03, 0xcd, 0x3a, 0x28, 0x1f, 0x01, 0xaf, 0x9e, 0xbc, 0x9f, 0xe8, 0x6e, 0x4b, 0x0f,
	0x13, 0xb9, 0xa5, 0xa5, 0xdf, 0x1d, 0x98, 0x3f, 0x1d, 0x7c, 0xdf, 0x16, 0xed, 0xdf, 0x86, 0x90,
	0xb0, 0xbb, 0x96, 0x35, 0x83, 0xea, 0x2e, 0xd3, 0x4f, 0xb8, 0xf8, 0x0a, 0x00, 0x00, 0xff, 0xff,
	0xda, 0x6c, 0x82, 0xb3, 0x96, 0x01, 0x00, 0x00,
}
