// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/query.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestList struct {
	Index                int64             `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Limit                int64             `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Gt                   int64             `protobuf:"varint,3,opt,name=gt,proto3" json:"gt,omitempty"`
	Lt                   int64             `protobuf:"varint,4,opt,name=lt,proto3" json:"lt,omitempty"`
	Params               map[string]string `protobuf:"bytes,5,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RequestList) Reset()         { *m = RequestList{} }
func (m *RequestList) String() string { return proto.CompactTextString(m) }
func (*RequestList) ProtoMessage()    {}
func (*RequestList) Descriptor() ([]byte, []int) {
	return fileDescriptor_5958159b9fcae252, []int{0}
}

func (m *RequestList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestList.Unmarshal(m, b)
}
func (m *RequestList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestList.Marshal(b, m, deterministic)
}
func (m *RequestList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestList.Merge(m, src)
}
func (m *RequestList) XXX_Size() int {
	return xxx_messageInfo_RequestList.Size(m)
}
func (m *RequestList) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestList.DiscardUnknown(m)
}

var xxx_messageInfo_RequestList proto.InternalMessageInfo

func (m *RequestList) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *RequestList) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *RequestList) GetGt() int64 {
	if m != nil {
		return m.Gt
	}
	return 0
}

func (m *RequestList) GetLt() int64 {
	if m != nil {
		return m.Lt
	}
	return 0
}

func (m *RequestList) GetParams() map[string]string {
	if m != nil {
		return m.Params
	}
	return nil
}

type RequestById struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestById) Reset()         { *m = RequestById{} }
func (m *RequestById) String() string { return proto.CompactTextString(m) }
func (*RequestById) ProtoMessage()    {}
func (*RequestById) Descriptor() ([]byte, []int) {
	return fileDescriptor_5958159b9fcae252, []int{1}
}

func (m *RequestById) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestById.Unmarshal(m, b)
}
func (m *RequestById) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestById.Marshal(b, m, deterministic)
}
func (m *RequestById) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestById.Merge(m, src)
}
func (m *RequestById) XXX_Size() int {
	return xxx_messageInfo_RequestById.Size(m)
}
func (m *RequestById) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestById.DiscardUnknown(m)
}

var xxx_messageInfo_RequestById proto.InternalMessageInfo

func (m *RequestById) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type RequestBySingleColumn struct {
	Column               string   `protobuf:"bytes,1,opt,name=column,proto3" json:"column,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestBySingleColumn) Reset()         { *m = RequestBySingleColumn{} }
func (m *RequestBySingleColumn) String() string { return proto.CompactTextString(m) }
func (*RequestBySingleColumn) ProtoMessage()    {}
func (*RequestBySingleColumn) Descriptor() ([]byte, []int) {
	return fileDescriptor_5958159b9fcae252, []int{2}
}

func (m *RequestBySingleColumn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestBySingleColumn.Unmarshal(m, b)
}
func (m *RequestBySingleColumn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestBySingleColumn.Marshal(b, m, deterministic)
}
func (m *RequestBySingleColumn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestBySingleColumn.Merge(m, src)
}
func (m *RequestBySingleColumn) XXX_Size() int {
	return xxx_messageInfo_RequestBySingleColumn.Size(m)
}
func (m *RequestBySingleColumn) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestBySingleColumn.DiscardUnknown(m)
}

var xxx_messageInfo_RequestBySingleColumn proto.InternalMessageInfo

func (m *RequestBySingleColumn) GetColumn() string {
	if m != nil {
		return m.Column
	}
	return ""
}

type ResponseEffect struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Effect               int64    `protobuf:"varint,2,opt,name=effect,proto3" json:"effect,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseEffect) Reset()         { *m = ResponseEffect{} }
func (m *ResponseEffect) String() string { return proto.CompactTextString(m) }
func (*ResponseEffect) ProtoMessage()    {}
func (*ResponseEffect) Descriptor() ([]byte, []int) {
	return fileDescriptor_5958159b9fcae252, []int{3}
}

func (m *ResponseEffect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseEffect.Unmarshal(m, b)
}
func (m *ResponseEffect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseEffect.Marshal(b, m, deterministic)
}
func (m *ResponseEffect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseEffect.Merge(m, src)
}
func (m *ResponseEffect) XXX_Size() int {
	return xxx_messageInfo_ResponseEffect.Size(m)
}
func (m *ResponseEffect) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseEffect.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseEffect proto.InternalMessageInfo

func (m *ResponseEffect) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ResponseEffect) GetEffect() int64 {
	if m != nil {
		return m.Effect
	}
	return 0
}

func init() {
	proto.RegisterType((*RequestList)(nil), "pb.requestList")
	proto.RegisterMapType((map[string]string)(nil), "pb.requestList.ParamsEntry")
	proto.RegisterType((*RequestById)(nil), "pb.requestById")
	proto.RegisterType((*RequestBySingleColumn)(nil), "pb.requestBySingleColumn")
	proto.RegisterType((*ResponseEffect)(nil), "pb.responseEffect")
}

func init() { proto.RegisterFile("pb/query.proto", fileDescriptor_5958159b9fcae252) }

var fileDescriptor_5958159b9fcae252 = []byte{
	// 269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0xc6, 0xc9, 0xe6, 0x6d, 0x5e, 0x3b, 0x81, 0x20, 0x8b, 0xca, 0xa2, 0x08, 0x25, 0xa7, 0x9e,
	0x52, 0xb0, 0x17, 0xf5, 0x58, 0xe9, 0x41, 0xf0, 0x20, 0xf1, 0x13, 0xe4, 0xcf, 0x34, 0x2c, 0x6e,
	0x92, 0xed, 0xee, 0x46, 0xcc, 0x47, 0xf4, 0x5b, 0x49, 0x26, 0x6b, 0xe9, 0x6d, 0x7e, 0xcf, 0x3c,
	0xcc, 0x3c, 0x33, 0x90, 0xe8, 0x72, 0x73, 0x1c, 0xd0, 0x8c, 0x99, 0x36, 0xbd, 0xeb, 0x39, 0xd3,
	0x65, 0xfa, 0x13, 0x40, 0x6c, 0xf0, 0x38, 0xa0, 0x75, 0x6f, 0xd2, 0x3a, 0x7e, 0x05, 0x0b, 0xd9,
	0xd5, 0xf8, 0x2d, 0x82, 0x55, 0xb0, 0x0e, 0xf3, 0x19, 0x26, 0x55, 0xc9, 0x56, 0x3a, 0xc1, 0x66,
	0x95, 0x80, 0x27, 0xc0, 0x1a, 0x27, 0x42, 0x92, 0x58, 0x43, 0xac, 0x9c, 0xf8, 0x37, 0xb3, 0x72,
	0x7c, 0x0b, 0x91, 0x2e, 0x4c, 0xd1, 0x5a, 0xb1, 0x58, 0x85, 0xeb, 0xf8, 0xe1, 0x2e, 0xd3, 0x65,
	0x76, 0xb6, 0x2c, 0x7b, 0xa7, 0xee, 0xbe, 0x73, 0x66, 0xcc, 0xbd, 0xf5, 0xf6, 0x09, 0xe2, 0x33,
	0x99, 0x5f, 0x42, 0xf8, 0x89, 0x23, 0xa5, 0x59, 0xe6, 0x53, 0x39, 0x65, 0xf9, 0x2a, 0xd4, 0x80,
	0x94, 0x65, 0x99, 0xcf, 0xf0, 0xcc, 0x1e, 0x83, 0xf4, 0xfe, 0x74, 0xca, 0x6e, 0x7c, 0xad, 0xa7,
	0x38, 0xb2, 0xf6, 0x77, 0x30, 0x59, 0xa7, 0x1b, 0xb8, 0x3e, 0xb5, 0x3f, 0x64, 0xd7, 0x28, 0x7c,
	0xe9, 0xd5, 0xd0, 0x76, 0xfc, 0x06, 0xa2, 0x8a, 0x2a, 0xbf, 0xc6, 0x53, 0xba, 0x83, 0xc4, 0xa0,
	0xd5, 0x7d, 0x67, 0x71, 0x7f, 0x38, 0x60, 0xe5, 0xb8, 0x80, 0xff, 0x76, 0xa8, 0x2a, 0xb4, 0x96,
	0xac, 0x17, 0xf9, 0x1f, 0x4e, 0x33, 0x90, 0x3c, 0xfe, 0x45, 0x9e, 0xca, 0x88, 0x5e, 0xbd, 0xfd,
	0x0d, 0x00, 0x00, 0xff, 0xff, 0xc7, 0xd7, 0x00, 0x8e, 0x7c, 0x01, 0x00, 0x00,
}
