// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/record.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Record struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Wid                  int64    `protobuf:"varint,2,opt,name=wid,proto3" json:"wid,omitempty"`
	Wuid                 int64    `protobuf:"varint,3,opt,name=wuid,proto3" json:"wuid,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=Type,proto3" json:"Type,omitempty"`
	Content              string   `protobuf:"bytes,5,opt,name=Content,proto3" json:"Content,omitempty"`
	CreatedAt            int64    `protobuf:"varint,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_efd369c7932b0890, []int{0}
}

func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Record) GetWid() int64 {
	if m != nil {
		return m.Wid
	}
	return 0
}

func (m *Record) GetWuid() int64 {
	if m != nil {
		return m.Wuid
	}
	return 0
}

func (m *Record) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Record) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Record) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

type RecordList struct {
	Index                int64     `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Limit                int64     `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Total                int64     `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Records              []*Record `protobuf:"bytes,4,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RecordList) Reset()         { *m = RecordList{} }
func (m *RecordList) String() string { return proto.CompactTextString(m) }
func (*RecordList) ProtoMessage()    {}
func (*RecordList) Descriptor() ([]byte, []int) {
	return fileDescriptor_efd369c7932b0890, []int{1}
}

func (m *RecordList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordList.Unmarshal(m, b)
}
func (m *RecordList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordList.Marshal(b, m, deterministic)
}
func (m *RecordList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordList.Merge(m, src)
}
func (m *RecordList) XXX_Size() int {
	return xxx_messageInfo_RecordList.Size(m)
}
func (m *RecordList) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordList.DiscardUnknown(m)
}

var xxx_messageInfo_RecordList proto.InternalMessageInfo

func (m *RecordList) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *RecordList) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *RecordList) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *RecordList) GetRecords() []*Record {
	if m != nil {
		return m.Records
	}
	return nil
}

func init() {
	proto.RegisterType((*Record)(nil), "pb.Record")
	proto.RegisterType((*RecordList)(nil), "pb.RecordList")
}

func init() { proto.RegisterFile("pb/record.proto", fileDescriptor_efd369c7932b0890) }

var fileDescriptor_efd369c7932b0890 = []byte{
	// 213 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0xd9, 0xcd, 0x76, 0x4b, 0x47, 0x50, 0x19, 0x3c, 0xcc, 0xc1, 0xc3, 0x52, 0x3c, 0xec,
	0x69, 0x05, 0x7d, 0x02, 0xf1, 0xea, 0x29, 0xf8, 0x02, 0x4d, 0x93, 0xc3, 0x40, 0xdd, 0x84, 0x74,
	0xa4, 0xfa, 0x0a, 0x3e, 0xb5, 0x64, 0xb2, 0x4b, 0x6f, 0xff, 0xff, 0x05, 0x32, 0xdf, 0x0c, 0xdc,
	0x25, 0xf7, 0x9c, 0xc3, 0x31, 0x66, 0x3f, 0xa5, 0x1c, 0x25, 0x62, 0x9b, 0xdc, 0xfe, 0xaf, 0x81,
	0xde, 0x2a, 0xc4, 0x5b, 0x68, 0xd9, 0x53, 0x33, 0x34, 0xa3, 0xb1, 0x2d, 0x7b, 0xbc, 0x07, 0x73,
	0x61, 0x4f, 0xad, 0x82, 0x12, 0x11, 0xa1, 0xbb, 0x7c, 0xb3, 0x27, 0xa3, 0x48, 0x73, 0x61, 0x9f,
	0xbf, 0x29, 0x50, 0x37, 0x34, 0xe3, 0xce, 0x6a, 0x46, 0x82, 0xed, 0x7b, 0x9c, 0x25, 0xcc, 0x42,
	0x1b, 0xc5, 0x6b, 0xc5, 0x47, 0xd8, 0x1d, 0x73, 0x38, 0x48, 0xf0, 0x6f, 0x42, 0xbd, 0x7e, 0x73,
	0x05, 0x7b, 0x01, 0xa8, 0x2e, 0x1f, 0x7c, 0x16, 0x7c, 0x80, 0x0d, 0xcf, 0x3e, 0xfc, 0x2c, 0x4a,
	0xb5, 0x14, 0x7a, 0xe2, 0x2f, 0x96, 0xc5, 0xab, 0x96, 0x42, 0x25, 0xca, 0xe1, 0xb4, 0xa8, 0xd5,
	0x82, 0x4f, 0xb0, 0xad, 0x0b, 0x9f, 0xa9, 0x1b, 0xcc, 0x78, 0xf3, 0x02, 0x53, 0x72, 0x53, 0x1d,
	0x61, 0xd7, 0x27, 0xd7, 0xeb, 0x35, 0x5e, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0xee, 0xa1, 0x65,
	0xfa, 0x20, 0x01, 0x00, 0x00,
}
