// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/reply.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReplyStatus int32

const (
	ReplyStatus_INIT         ReplyStatus = 0
	ReplyStatus_OPEN         ReplyStatus = 1
	ReplyStatus_MANUAL_CLOSE ReplyStatus = 2
	ReplyStatus_AUTO_CLOSE   ReplyStatus = 3
)

var ReplyStatus_name = map[int32]string{
	0: "INIT",
	1: "OPEN",
	2: "MANUAL_CLOSE",
	3: "AUTO_CLOSE",
}

var ReplyStatus_value = map[string]int32{
	"INIT":         0,
	"OPEN":         1,
	"MANUAL_CLOSE": 2,
	"AUTO_CLOSE":   3,
}

func (x ReplyStatus) String() string {
	return proto.EnumName(ReplyStatus_name, int32(x))
}

func (ReplyStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fca2ff5f393a9201, []int{0}
}

type Reply struct {
	Id                   int64       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Wid                  int64       `protobuf:"varint,2,opt,name=wid,proto3" json:"wid,omitempty"`
	ActivityId           int64       `protobuf:"varint,3,opt,name=activityId,proto3" json:"activityId,omitempty"`
	Alias                string      `protobuf:"bytes,4,opt,name=alias,proto3" json:"alias,omitempty"`
	ClickKey             string      `protobuf:"bytes,5,opt,name=clickKey,proto3" json:"clickKey,omitempty"`
	Success              string      `protobuf:"bytes,6,opt,name=success,proto3" json:"success,omitempty"`
	Fail                 string      `protobuf:"bytes,7,opt,name=fail,proto3" json:"fail,omitempty"`
	NoPrizeReturn        string      `protobuf:"bytes,8,opt,name=noPrizeReturn,proto3" json:"noPrizeReturn,omitempty"`
	Extra                string      `protobuf:"bytes,9,opt,name=extra,proto3" json:"extra,omitempty"`
	Type                 string      `protobuf:"bytes,10,opt,name=type,proto3" json:"type,omitempty"`
	Match                string      `protobuf:"bytes,11,opt,name=match,proto3" json:"match,omitempty"`
	Status               ReplyStatus `protobuf:"varint,12,opt,name=status,proto3,enum=pb.ReplyStatus" json:"status,omitempty"`
	CreatedAt            int64       `protobuf:"varint,13,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            int64       `protobuf:"varint,14,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Reply) Reset()         { *m = Reply{} }
func (m *Reply) String() string { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()    {}
func (*Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_fca2ff5f393a9201, []int{0}
}

func (m *Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reply.Unmarshal(m, b)
}
func (m *Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reply.Marshal(b, m, deterministic)
}
func (m *Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reply.Merge(m, src)
}
func (m *Reply) XXX_Size() int {
	return xxx_messageInfo_Reply.Size(m)
}
func (m *Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_Reply proto.InternalMessageInfo

func (m *Reply) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Reply) GetWid() int64 {
	if m != nil {
		return m.Wid
	}
	return 0
}

func (m *Reply) GetActivityId() int64 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *Reply) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *Reply) GetClickKey() string {
	if m != nil {
		return m.ClickKey
	}
	return ""
}

func (m *Reply) GetSuccess() string {
	if m != nil {
		return m.Success
	}
	return ""
}

func (m *Reply) GetFail() string {
	if m != nil {
		return m.Fail
	}
	return ""
}

func (m *Reply) GetNoPrizeReturn() string {
	if m != nil {
		return m.NoPrizeReturn
	}
	return ""
}

func (m *Reply) GetExtra() string {
	if m != nil {
		return m.Extra
	}
	return ""
}

func (m *Reply) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Reply) GetMatch() string {
	if m != nil {
		return m.Match
	}
	return ""
}

func (m *Reply) GetStatus() ReplyStatus {
	if m != nil {
		return m.Status
	}
	return ReplyStatus_INIT
}

func (m *Reply) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Reply) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type ReplyList struct {
	Index                int64    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Limit                int64    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Total                int64    `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Replies              []*Reply `protobuf:"bytes,4,rep,name=replies,proto3" json:"replies,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplyList) Reset()         { *m = ReplyList{} }
func (m *ReplyList) String() string { return proto.CompactTextString(m) }
func (*ReplyList) ProtoMessage()    {}
func (*ReplyList) Descriptor() ([]byte, []int) {
	return fileDescriptor_fca2ff5f393a9201, []int{1}
}

func (m *ReplyList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyList.Unmarshal(m, b)
}
func (m *ReplyList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyList.Marshal(b, m, deterministic)
}
func (m *ReplyList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyList.Merge(m, src)
}
func (m *ReplyList) XXX_Size() int {
	return xxx_messageInfo_ReplyList.Size(m)
}
func (m *ReplyList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyList proto.InternalMessageInfo

func (m *ReplyList) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *ReplyList) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ReplyList) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ReplyList) GetReplies() []*Reply {
	if m != nil {
		return m.Replies
	}
	return nil
}

type StatusByWidActivityId struct {
	Wid                  int64       `protobuf:"varint,1,opt,name=wid,proto3" json:"wid,omitempty"`
	ActivityId           int64       `protobuf:"varint,2,opt,name=activityId,proto3" json:"activityId,omitempty"`
	Status               ReplyStatus `protobuf:"varint,3,opt,name=status,proto3,enum=pb.ReplyStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *StatusByWidActivityId) Reset()         { *m = StatusByWidActivityId{} }
func (m *StatusByWidActivityId) String() string { return proto.CompactTextString(m) }
func (*StatusByWidActivityId) ProtoMessage()    {}
func (*StatusByWidActivityId) Descriptor() ([]byte, []int) {
	return fileDescriptor_fca2ff5f393a9201, []int{2}
}

func (m *StatusByWidActivityId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusByWidActivityId.Unmarshal(m, b)
}
func (m *StatusByWidActivityId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusByWidActivityId.Marshal(b, m, deterministic)
}
func (m *StatusByWidActivityId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusByWidActivityId.Merge(m, src)
}
func (m *StatusByWidActivityId) XXX_Size() int {
	return xxx_messageInfo_StatusByWidActivityId.Size(m)
}
func (m *StatusByWidActivityId) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusByWidActivityId.DiscardUnknown(m)
}

var xxx_messageInfo_StatusByWidActivityId proto.InternalMessageInfo

func (m *StatusByWidActivityId) GetWid() int64 {
	if m != nil {
		return m.Wid
	}
	return 0
}

func (m *StatusByWidActivityId) GetActivityId() int64 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *StatusByWidActivityId) GetStatus() ReplyStatus {
	if m != nil {
		return m.Status
	}
	return ReplyStatus_INIT
}

func init() {
	proto.RegisterEnum("pb.ReplyStatus", ReplyStatus_name, ReplyStatus_value)
	proto.RegisterType((*Reply)(nil), "pb.Reply")
	proto.RegisterType((*ReplyList)(nil), "pb.ReplyList")
	proto.RegisterType((*StatusByWidActivityId)(nil), "pb.StatusByWidActivityId")
}

func init() { proto.RegisterFile("pb/reply.proto", fileDescriptor_fca2ff5f393a9201) }

var fileDescriptor_fca2ff5f393a9201 = []byte{
	// 402 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xdd, 0xea, 0xd3, 0x40,
	0x10, 0xc5, 0x4d, 0xd2, 0xaf, 0x4c, 0xff, 0x8d, 0x61, 0x50, 0x58, 0x44, 0xa4, 0x54, 0xc1, 0xe0,
	0x45, 0x85, 0xfa, 0x04, 0xb1, 0xf4, 0xa2, 0x58, 0xdb, 0x92, 0xb6, 0x78, 0x29, 0x9b, 0xec, 0x8a,
	0x8b, 0x69, 0x13, 0x36, 0x1b, 0x6d, 0x7c, 0x6e, 0x1f, 0x40, 0x76, 0x37, 0xfd, 0x10, 0xd1, 0xbb,
	0x39, 0xbf, 0xb3, 0x0c, 0x93, 0x73, 0x02, 0x41, 0x99, 0xbe, 0x95, 0xbc, 0xcc, 0x9b, 0x69, 0x29,
	0x0b, 0x55, 0xa0, 0x5b, 0xa6, 0x93, 0x5f, 0x2e, 0x74, 0x13, 0xcd, 0x30, 0x00, 0x57, 0x30, 0xe2,
	0x8c, 0x9d, 0xc8, 0x4b, 0x5c, 0xc1, 0x30, 0x04, 0xef, 0x87, 0x60, 0xc4, 0x35, 0x40, 0x8f, 0xf8,
	0x02, 0x80, 0x66, 0x4a, 0x7c, 0x17, 0xaa, 0x59, 0x32, 0xe2, 0x19, 0xe3, 0x8e, 0xe0, 0x13, 0xe8,
	0xd2, 0x5c, 0xd0, 0x8a, 0x74, 0xc6, 0x4e, 0xe4, 0x27, 0x56, 0xe0, 0x33, 0x18, 0x64, 0xb9, 0xc8,
	0xbe, 0x7d, 0xe0, 0x0d, 0xe9, 0x1a, 0xe3, 0xaa, 0x91, 0x40, 0xbf, 0xaa, 0xb3, 0x8c, 0x57, 0x15,
	0xe9, 0x19, 0xeb, 0x22, 0x11, 0xa1, 0xf3, 0x85, 0x8a, 0x9c, 0xf4, 0x0d, 0x36, 0x33, 0xbe, 0x82,
	0xd1, 0xa9, 0xd8, 0x4a, 0xf1, 0x93, 0x27, 0x5c, 0xd5, 0xf2, 0x44, 0x06, 0xc6, 0xfc, 0x13, 0xea,
	0x2b, 0xf8, 0x59, 0x49, 0x4a, 0x7c, 0x7b, 0x85, 0x11, 0x7a, 0x9f, 0x6a, 0x4a, 0x4e, 0xc0, 0xee,
	0xd3, 0xb3, 0x7e, 0x79, 0xa4, 0x2a, 0xfb, 0x4a, 0x86, 0xf6, 0xa5, 0x11, 0xf8, 0x1a, 0x7a, 0x95,
	0xa2, 0xaa, 0xae, 0xc8, 0xc3, 0xd8, 0x89, 0x82, 0xd9, 0xe3, 0x69, 0x99, 0x4e, 0x4d, 0x44, 0x3b,
	0x83, 0x93, 0xd6, 0xc6, 0xe7, 0xe0, 0x67, 0x92, 0x53, 0xc5, 0x59, 0xac, 0xc8, 0xc8, 0xa4, 0x71,
	0x03, 0xda, 0xad, 0x4b, 0xd6, 0xba, 0x81, 0x75, 0xaf, 0x60, 0x22, 0xc1, 0x37, 0x2b, 0x57, 0xa2,
	0x52, 0xfa, 0x0e, 0x71, 0x62, 0xfc, 0xdc, 0x86, 0x6f, 0x85, 0xa6, 0xb9, 0x38, 0x0a, 0xd5, 0x36,
	0x60, 0x85, 0xa6, 0xaa, 0x50, 0x34, 0x6f, 0xe3, 0xb7, 0x02, 0x5f, 0x42, 0x5f, 0x17, 0x2b, 0xb8,
	0xce, 0xde, 0x8b, 0x86, 0x33, 0xff, 0x7a, 0x74, 0x72, 0x71, 0x26, 0x12, 0x9e, 0xda, 0x2f, 0x78,
	0xdf, 0x7c, 0x12, 0x2c, 0xbe, 0xf5, 0xd6, 0x36, 0xed, 0xfc, 0xab, 0x69, 0xf7, 0xaf, 0xa6, 0x6f,
	0x19, 0x79, 0xff, 0xcd, 0xe8, 0xcd, 0x1c, 0x86, 0x77, 0x18, 0x07, 0xd0, 0x59, 0xae, 0x97, 0xfb,
	0xf0, 0x91, 0x9e, 0x36, 0xdb, 0xc5, 0x3a, 0x74, 0x30, 0x84, 0x87, 0x8f, 0xf1, 0xfa, 0x10, 0xaf,
	0x3e, 0xcf, 0x57, 0x9b, 0xdd, 0x22, 0x74, 0x31, 0x00, 0x88, 0x0f, 0xfb, 0x4d, 0xab, 0xbd, 0xb4,
	0x67, 0x7e, 0xd7, 0x77, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xc0, 0xfe, 0xba, 0x5d, 0xc0, 0x02,
	0x00, 0x00,
}
