// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/wechat.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Wechat struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Appid                string   `protobuf:"bytes,3,opt,name=appid,proto3" json:"appid,omitempty"`
	Appsecret            string   `protobuf:"bytes,4,opt,name=appsecret,proto3" json:"appsecret,omitempty"`
	EncodingAesKey       string   `protobuf:"bytes,5,opt,name=encodingAesKey,proto3" json:"encodingAesKey,omitempty"`
	Token                string   `protobuf:"bytes,6,opt,name=Token,proto3" json:"Token,omitempty"`
	Flag                 string   `protobuf:"bytes,7,opt,name=flag,proto3" json:"flag,omitempty"`
	Type                 int32    `protobuf:"varint,8,opt,name=Type,proto3" json:"Type,omitempty"`
	Pass                 bool     `protobuf:"varint,9,opt,name=Pass,proto3" json:"Pass,omitempty"`
	SaveInput            bool     `protobuf:"varint,10,opt,name=SaveInput,proto3" json:"SaveInput,omitempty"`
	NeedSaveMen          bool     `protobuf:"varint,11,opt,name=NeedSaveMen,proto3" json:"NeedSaveMen,omitempty"`
	CreatedAt            int64    `protobuf:"varint,12,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,13,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Wechat) Reset()         { *m = Wechat{} }
func (m *Wechat) String() string { return proto.CompactTextString(m) }
func (*Wechat) ProtoMessage()    {}
func (*Wechat) Descriptor() ([]byte, []int) {
	return fileDescriptor_6743305892b52164, []int{0}
}

func (m *Wechat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Wechat.Unmarshal(m, b)
}
func (m *Wechat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Wechat.Marshal(b, m, deterministic)
}
func (m *Wechat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Wechat.Merge(m, src)
}
func (m *Wechat) XXX_Size() int {
	return xxx_messageInfo_Wechat.Size(m)
}
func (m *Wechat) XXX_DiscardUnknown() {
	xxx_messageInfo_Wechat.DiscardUnknown(m)
}

var xxx_messageInfo_Wechat proto.InternalMessageInfo

func (m *Wechat) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Wechat) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Wechat) GetAppid() string {
	if m != nil {
		return m.Appid
	}
	return ""
}

func (m *Wechat) GetAppsecret() string {
	if m != nil {
		return m.Appsecret
	}
	return ""
}

func (m *Wechat) GetEncodingAesKey() string {
	if m != nil {
		return m.EncodingAesKey
	}
	return ""
}

func (m *Wechat) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Wechat) GetFlag() string {
	if m != nil {
		return m.Flag
	}
	return ""
}

func (m *Wechat) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Wechat) GetPass() bool {
	if m != nil {
		return m.Pass
	}
	return false
}

func (m *Wechat) GetSaveInput() bool {
	if m != nil {
		return m.SaveInput
	}
	return false
}

func (m *Wechat) GetNeedSaveMen() bool {
	if m != nil {
		return m.NeedSaveMen
	}
	return false
}

func (m *Wechat) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Wechat) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type WechatList struct {
	Index                int64     `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Limit                int64     `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Total                int64     `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Wechats              []*Wechat `protobuf:"bytes,4,rep,name=wechats,proto3" json:"wechats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *WechatList) Reset()         { *m = WechatList{} }
func (m *WechatList) String() string { return proto.CompactTextString(m) }
func (*WechatList) ProtoMessage()    {}
func (*WechatList) Descriptor() ([]byte, []int) {
	return fileDescriptor_6743305892b52164, []int{1}
}

func (m *WechatList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WechatList.Unmarshal(m, b)
}
func (m *WechatList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WechatList.Marshal(b, m, deterministic)
}
func (m *WechatList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WechatList.Merge(m, src)
}
func (m *WechatList) XXX_Size() int {
	return xxx_messageInfo_WechatList.Size(m)
}
func (m *WechatList) XXX_DiscardUnknown() {
	xxx_messageInfo_WechatList.DiscardUnknown(m)
}

var xxx_messageInfo_WechatList proto.InternalMessageInfo

func (m *WechatList) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *WechatList) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *WechatList) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *WechatList) GetWechats() []*Wechat {
	if m != nil {
		return m.Wechats
	}
	return nil
}

func init() {
	proto.RegisterType((*Wechat)(nil), "pb.Wechat")
	proto.RegisterType((*WechatList)(nil), "pb.WechatList")
}

func init() { proto.RegisterFile("pb/wechat.proto", fileDescriptor_6743305892b52164) }

var fileDescriptor_6743305892b52164 = []byte{
	// 309 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xcd, 0x4e, 0xc3, 0x30,
	0x10, 0x84, 0x95, 0xa4, 0xbf, 0x5b, 0x28, 0x92, 0xc5, 0x61, 0x0f, 0x1c, 0xa2, 0x0a, 0xa1, 0x9c,
	0x8a, 0x04, 0x4f, 0xd0, 0x23, 0xe2, 0x47, 0xc8, 0x54, 0xe2, 0xec, 0xc4, 0x4b, 0xb1, 0x68, 0x1d,
	0xab, 0x76, 0x81, 0xbe, 0x28, 0xcf, 0x83, 0xbc, 0x2e, 0x04, 0x71, 0x9b, 0xf9, 0x26, 0xd9, 0x6c,
	0x66, 0xe1, 0xc4, 0xd5, 0x97, 0x1f, 0xd4, 0xbc, 0xaa, 0x30, 0x77, 0xdb, 0x36, 0xb4, 0x22, 0x77,
	0xf5, 0xec, 0x2b, 0x87, 0xc1, 0x33, 0x43, 0x31, 0x85, 0xdc, 0x68, 0xcc, 0xca, 0xac, 0x2a, 0x64,
	0x6e, 0xb4, 0x10, 0xd0, 0xb3, 0x6a, 0x43, 0x98, 0x97, 0x59, 0x35, 0x96, 0xac, 0xc5, 0x29, 0xf4,
	0x95, 0x73, 0x46, 0x63, 0xc1, 0x30, 0x19, 0x71, 0x06, 0x63, 0xe5, 0x9c, 0xa7, 0x66, 0x4b, 0x01,
	0x7b, 0x9c, 0x74, 0x40, 0x5c, 0xc0, 0x94, 0x6c, 0xd3, 0x6a, 0x63, 0x57, 0x0b, 0xf2, 0xb7, 0xb4,
	0xc7, 0x3e, 0x3f, 0xf2, 0x8f, 0xc6, 0xd9, 0xcb, 0xf6, 0x8d, 0x2c, 0x0e, 0xd2, 0x6c, 0x36, 0x71,
	0x8b, 0x97, 0xb5, 0x5a, 0xe1, 0x30, 0x6d, 0x11, 0x75, 0x64, 0xcb, 0xbd, 0x23, 0x1c, 0x95, 0x59,
	0xd5, 0x97, 0xac, 0x23, 0x7b, 0x54, 0xde, 0xe3, 0xb8, 0xcc, 0xaa, 0x91, 0x64, 0x1d, 0xf7, 0x7a,
	0x52, 0xef, 0x74, 0x63, 0xdd, 0x2e, 0x20, 0x70, 0xd0, 0x01, 0x51, 0xc2, 0xe4, 0x81, 0x48, 0x47,
	0x70, 0x4f, 0x16, 0x27, 0x9c, 0xff, 0x45, 0xf1, 0xfd, 0x66, 0x4b, 0x2a, 0x90, 0x5e, 0x04, 0x3c,
	0xe2, 0x62, 0x3a, 0x10, 0xd3, 0x9d, 0xd3, 0x87, 0xf4, 0x38, 0xa5, 0xbf, 0x60, 0x16, 0x00, 0x52,
	0xaf, 0x77, 0xc6, 0x87, 0xf8, 0x6f, 0xc6, 0x6a, 0xfa, 0x3c, 0xd4, 0x9b, 0x4c, 0xa4, 0x6b, 0xb3,
	0x31, 0x81, 0x2b, 0x2e, 0x64, 0x32, 0x91, 0x86, 0x36, 0xa8, 0x35, 0x77, 0x5c, 0xc8, 0x64, 0xc4,
	0x39, 0x0c, 0xd3, 0xf1, 0x3c, 0xf6, 0xca, 0xa2, 0x9a, 0x5c, 0xc1, 0xdc, 0xd5, 0xf3, 0xf4, 0x09,
	0xf9, 0x13, 0xd5, 0x03, 0xbe, 0xec, 0xf5, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6a, 0x93, 0x7a,
	0x21, 0xec, 0x01, 0x00, 0x00,
}
